BaseJumpContracts/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BaseJumpContracts.Models
{
    public class Customer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        
        public virtual ICollection<Subscription> Subscriptions { get; set; }
    }
}

BaseJumpContracts/Controllers/CustomerController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using BaseJumpContracts.DAL;
using BaseJumpContracts.Models;
using iTextSharp.text;
using System.IO;
using iTextSharp.text.pdf;
using System;

namespace BaseJumpContracts.Controllers
{
    public class CustomerController : Controller
    {
        private ContractContext db = new ContractContext();

        // GET: Customer
        public ActionResult Index()
        {
            /*
            //TODO: Factor all this out into a public function that all controllers can use
            int counter = 0;
            string checker =  "BJC" + counter.ToString() + "timeStamp";
            while (Request.Cookies[checker] != null)
            {
                var ID = counter;

                var timeStampKey = "BJC" + counter.ToString() + "timeStamp";
                var timeStamp = Request.Cookies[timeStampKey].Value;

                System.Diagnostics.Debug.WriteLine(timeStamp);

                //Event type

                //Class

                //Write all this shit to the database

                counter++;
                checker =  "BJC" + counter.ToString() + "timeStamp";
            }

            Request.Cookies.Clear();
            */

            return View(db.Customers.ToList());
        }

        // GET: Customer/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
                
            return View(customer);
        }

        // GET: Customer/Contract/5
        public FileResult Contract(int? id)
        {
            //Find customer
            Customer customer = db.Customers.Find(id);
            //Extract subscriptions
            var subscriptions = customer.Subscriptions;
            //Caculate total price
            List<decimal> prices = new List<decimal>();
            foreach (var subscription in subscriptions) {
                prices.Add(subscription.Price);
            }
            var totalPrice = prices.Sum();

            //Initialize
            var document = new Document(PageSize.A4, 50, 50, 25, 25);
            var output = new MemoryStream();
            var writer = PdfWriter.GetInstance(document, output);
            document.Open();

            //Define fonts
            var titleFont = FontFactory.GetFont("Arial", 18, Font.BOLD);
            var subTitleFont = FontFactory.GetFont("Arial", 14, Font.BOLD);
            var boldTableFont = FontFactory.GetFont("Arial", 12, Font.BOLD);
            var endingMessageFont = FontFactory.GetFont("Arial", 10, Font.ITALIC);
            var bodyFont = FontFactory.GetFont("Arial", 12, Font.NORMAL);

            //Build document
            document.Add(new Paragraph(customer.Name, titleFont));

            var subscriptionsTable = new PdfPTable(4);

            //Format table
            subscriptionsTable.HorizontalAlignment = 0;
            subscriptionsTable.SpacingBefore = 10;
            subscriptionsTable.SpacingAfter = 10;
            subscriptionsTable.DefaultCell.Border = 1;
            subscriptionsTable.DefaultCell.Padding = 10;

            //Table Header
            subscriptionsTable.AddCell("Service ID");
            subscriptionsTable.AddCell("Name");
            subscriptionsTable.AddCell("Price");
            subscriptionsTable.AddCell("Term");

            //Build table values
            foreach(var subscription in subscriptions)
            {
                var service = subscription.Service;
                subscriptionsTable.AddCell(new Phrase(service.ID.ToString()));
                subscriptionsTable.AddCell(new Phrase(service.Name));
                subscriptionsTable.AddCell(new Phrase(subscription.Price.ToString()));
                subscriptionsTable.AddCell(new Phrase(subscription.Term.ToString()));
            }

            document.Add(subscriptionsTable);

            document.Add(new Paragraph(string.Format("Total Monthly Recurring Charges: ${0}", totalPrice), bodyFont));
            document.Add(new Paragraph(" "));
            document.Add(new Paragraph("Sign:__________________________________________"));
            document.Add(new Paragraph("Print Name:____________________________________"));
            document.Add(new Paragraph("Date:__________________________________________"));

            //Close stream and cast to byte array
            document.Close();
            byte[] content = output.ToArray();

            return File(content, "application/pdf", string.Format("{0}.pdf", customer.Name));
        }

        // GET: Customer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        // GET: Customer/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customer/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customer/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BaseJumpContracts/Controllers/SubscriptionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BaseJumpContracts.DAL;
using BaseJumpContracts.Models;

namespace BaseJumpContracts.Controllers
{
    public class SubscriptionController : Controller
    {
        private ContractContext db = new ContractContext();

        // GET: Subscription/Create
        public ActionResult Create(int customerID)
        {
            ViewBag.CustomerID = customerID;
            ViewBag.ServiceID = new SelectList(db.Services, "ID", "Name");
            return View();
        }

        // POST: Subscription/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SubscriptionID,CustomerID,ServiceID,Price,Term")] Subscription subscription)
        {
            var customerID = subscription.CustomerID;
            if (ModelState.IsValid)
            {
                db.Subscriptions.Add(subscription);
                db.SaveChanges();
                return RedirectToAction("Details", "Customer", new { ID = customerID });
            }

            ViewBag.CustomerID = customerID;
            ViewBag.ServiceID = new SelectList(db.Services, "ID", "Name", subscription.ServiceID);
            return View(subscription);
        }

        // GET: Subscription/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subscription subscription = db.Subscriptions.Find(id);
            if (subscription == null)
            {
                return HttpNotFound();
            }
            return View(subscription);
        }

        // POST: Subscription/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Subscription subscription = db.Subscriptions.Find(id);
            db.Subscriptions.Remove(subscription);
            db.SaveChanges();
            return RedirectToAction("Details", "Customer", new { id = subscription.CustomerID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BaseJumpContracts/Views/Customer/Create.cshtml
@model BaseJumpContracts.Models.Customer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BaseJumpContracts/Views/Customer/Delete.cshtml
@model BaseJumpContracts.Models.Customer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BaseJumpContracts/Views/Customer/Details.cshtml
@model BaseJumpContracts.Models.Customer

@{
    ViewBag.Title = "Details";
}

<h2>@Html.DisplayFor(model => model.Name)</h2>

<p>@Html.ActionLink("Edit Customer", "Edit", new { id = Model.ID })</p>

<div>
    
    <h3>
    @Html.DisplayNameFor(model => model.Subscriptions)
    </h3>
    <table>
        <tr>
            <th>Service ID</th>
            <th>Name</th>
            <th>Description</th>
        </tr>
        
        @foreach (var item in Model.Subscriptions)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Service.ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Service.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Service.Description)
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", "Subscription", new { id = item.SubscriptionID }, null)
                </td>
            </tr>
        }

    </table>
   <p class="under-table">
    @Html.ActionLink("Add Subscription", "Create", "Subscription", new { customerID = Model.ID }, null) | 
    @Html.ActionLink("Get Contract PDF", "Contract", new { id = Model.ID })
   </p>
</div>
<p>
    
    @Html.ActionLink("Back to Search", "Index")
</p>

BaseJumpContracts/Views/Customer/Edit.cshtml
@model BaseJumpContracts.Models.Customer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Customer", "Details", "Customer", new { ID = Model.ID }, null) | @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BaseJumpContracts/Views/Customer/Index.cshtml
@model IEnumerable<BaseJumpContracts.Models.Customer>

@{
    ViewBag.Title = "Search";
}

<h2 class="search-header">Search</h2>

<p>
    Search form will go here
</p>
<table class="index-table">

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(@Html.DisplayFor(modelItem => item.ID).ToHtmlString(), "Details", "Customer", new { ID = item.ID }, null)
        </td>
        <td>
            @Html.ActionLink(item.Name, "Details", "Customer", new { ID = item.ID }, null)
        </td>
    </tr>
}

</table>